### ISSUE TITLE
Anexar archivos adicionales

### ISSUE THREAD

**Issue by JuanPabloRG** [JuanPabloRG/practica-2164526#4]
Se tienen que anexar los siguientes archivos:

Documento con métodos de investigación
documento con la recolección de datos 
documentacion con la tabulacion de los datos y graficas
modelo canvas
mapas de proceso
definición de los requerimientos funcionales y no funcionales

**Comment by batobon** [comment]
Tarea de agregar los anexables lista

**Comment by MateoM-xl** [comment]
Tarea de agregar los anexables lista

**Comment by JuanPabloRG** [comment]
Tarea de agregar los anexables lista, aqui la evidencia
![WhatsApp Image 2021-07-02 at 3 09 38 PM](https://user-images.githubusercontent.com/34499412/124325579-862b9c80-db4a-11eb-99b8-40c75ffe5fd5.jpeg)
